// Generated by update-gallery.js.
window.JACKPOT_GALLERY = [
  {
    "src": "img/unnamed (1).webp",
    "alt": "Completed roofing project 1 by Jackpot Roofing & Gutters"
  },
  {
    "src": "img/unnamed (2).webp",
    "alt": "Completed roofing project 2 by Jackpot Roofing & Gutters"
  },
  {
    "src": "img/unnamed (3).webp",
    "alt": "Completed roofing project 3 by Jackpot Roofing & Gutters"
  }
];
