const fs = require('fs');
const path = require('path');

const imageDir = path.join(__dirname, 'img');
const output = path.join(__dirname, 'gallery-data.js');
const supported = new Set(['.jpg', '.jpeg', '.png', '.webp', '.gif', '.avif']);
const excluded = new Set(['jackpot-roofing-logo.jpg']);

const files = fs.readdirSync(imageDir)
  .filter((file) => supported.has(path.extname(file).toLowerCase()))
  .filter((file) => !excluded.has(file.toLowerCase()))
  .sort((a, b) => a.localeCompare(b, undefined, { numeric: true }));

const photos = files.map((file, index) => ({
  src: `img/${file}`,
  alt: `Completed roofing project ${index + 1} by Jackpot Roofing & Gutters`
}));

const contents = `// Generated by update-gallery.js.\nwindow.JACKPOT_GALLERY = ${JSON.stringify(photos, null, 2)};\n`;
fs.writeFileSync(output, contents);
console.log(`Gallery updated with ${files.length} project photo${files.length === 1 ? '' : 's'}.`);
